### ISSUE TITLE
macOS11运行demo-websocket兼容性问题

### ISSUE THREAD

**Issue by forestyoung23** [xkcoding/spring-boot-demo#184]
### 描述问题
macOS Big Sur 11.1版本运行demo-websocket模块报java.lang.UnsatisfiedLinkError: Unable to load library 'DiskArbitration'错误
```bash
java.lang.UnsatisfiedLinkError: Unable to load library 'DiskArbitration': Native library (darwin/libDiskArbitration.dylib) not found in resource path
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303) ~[jna-4.5.2.jar:4.5.2 (b0)]
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427) ~[jna-4.5.2.jar:4.5.2 (b0)]
        at com.sun.jna.Library$Handler.<init>(Library.java:179) ~[jna-4.5.2.jar:4.5.2 (b0)]
        at com.sun.jna.Native.loadLibrary(Native.java:569) ~[jna-4.5.2.jar:4.5.2 (b0)]
        at com.sun.jna.Native.loadLibrary(Native.java:544) ~[jna-4.5.2.jar:4.5.2 (b0)]
        at oshi.jna.platform.mac.DiskArbitration.<clinit>(DiskArbitration.java:36) ~[oshi-core-3.9.1.jar:3.9.1]
        at oshi.software.os.mac.MacFileSystem.getFileStores(MacFileSystem.java:75) ~[oshi-core-3.9.1.jar:3.9.1]
        at com.xkcoding.websocket.model.Server.setSysFiles(Server.java:176) ~[classes/:na]
        at com.xkcoding.websocket.model.Server.copyTo(Server.java:110) ~[classes/:na]
```

### 截屏或录像
![image](https://user-images.githubusercontent.com/62150631/107202458-2fa3b180-6a35-11eb-964c-28d80678a6c0.png)

**Comment by SuMiaoALi** [comment]
用netty自带的websocket，很简单实现，且并发也高
