### ISSUE TITLE
新建一个 spring-boot-demo-admin-client demo，不能成功向 server 注册

### ISSUE THREAD

**Issue by liuguangchuang** [xkcoding/spring-boot-demo#82]
### 创建一个 spring-boot-demo-admin-client demo，不能成功向 server 注册

根据示例 spring-boot-demo-admin-client 创建了一个 demo，client 和 server 都能启动成功，但是 client 就是不能向 server 注册，一直在报错，错误信息如下：
```
2020-01-04 16:48:12.510  INFO 6784 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path '/demo'
2020-01-04 16:48:12.514  INFO 6784 --- [           main] .l.SpringBootDemo4AdminClientApplication : Started SpringBootDemo4AdminClientApplication in 3.586 seconds (JVM running for 4.44)
2020-01-04 16:48:12.542 ERROR 6784 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: Either health or status endpoint must be enabled!
```

server 端也出现了错误：
```
2020-01-04 16:51:31.827 ERROR 4276 --- [nio-8000-exec-3] o.a.catalina.connector.CoyoteAdapter     : Exception while processing an asynchronous request

java.lang.IllegalStateException: Calling [asyncError()] is not valid for a request with Async state [MUST_DISPATCH]
	at org.apache.coyote.AsyncStateMachine.asyncError(AsyncStateMachine.java:440) ~[tomcat-embed-core-9.0.12.jar:9.0.12]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:494) [tomcat-embed-core-9.0.12.jar:9.0.12]
```

根据[官方文档](https://codecentric.github.io/spring-boot-admin/2.1.0/)来也是一样的错误，多次对比仓库中的 demo，没见有什么区别，仓库中的 client 能够 server 注册。

求解。感谢。

![client](https://user-images.githubusercontent.com/19651293/71763097-d0f73480-2f12-11ea-8abe-0325660e6118.png)
![server](https://user-images.githubusercontent.com/19651293/71763098-d0f73480-2f12-11ea-9d75-e9acba16a0a6.png)

**Comment by xkcoding** [comment]
是运行我的demo出错了吗，还是新建的一个 client，注册不上去

如果是新建的 client，建议先检查下 spring boot 版本与我示例中是否一样

再检查下actuator endpoint 是否开启

**Comment by liuguangchuang** [comment]
> 是运行我的demo出错了吗，还是新建的一个 client，注册不上去
> 
> 如果是新建的 client，建议先检查下 spring boot 版本与我示例中是否一样
> 
> 再检查下actuator endpoint 是否开启

**Comment by liuguangchuang** [comment]
> 是运行我的demo出错了吗，还是新建的一个 client，注册不上去
> 
> 如果是新建的 client，建议先检查下 spring boot 版本与我示例中是否一样
> 
> 再检查下actuator endpoint 是否开启

你的 demo 没错，是我敲错了一个单词

**Comment by xkcoding** [comment]
哈哈哈，仔细一点哈~
